### ISSUE TITLE
No TuneOut Directory in /Library/Application Support

### ISSUE THREAD

**Issue by dyllandry** [purrloftruth/tuneout#15]
Just downloaded version 0.8. It's up and running, though never is a folder created in my Application Support directory called TuneOut.

I'm running Mac OS Mojave 10.14.3 (18D109).

**Comment by purrloftruth** [comment]
Hi, apologies for the delay in responding, I don't check GitHub frequently right now!

On Mojave, because of changes made to further harden macOS, if you didn't receive prompts when the app was first run, I believe you'll need to go to System Preferences -> Security & Privacy -> Privacy and manually add TuneOut to both the "Accessibility" and "Full Disk Access" lists. Please let me know if this doesn't resolve the issue.

Hopefully at some point I'll be able to work on the successor app (which thankfully sidesteps these issues) that I'd been working on a bit further and at least get an initial release made available, but my health is not great at the moment so I don't get to spend too much time on these things.

**Comment by dyllandry** [comment]
I was looking in the wrong folder — in `/Library/Application Support` ! I did not know you had to manually reveal your `~/Library` folder by navigating to your home directory, clicking View -> Show View Options, then Show Library Folder. The directory may have been there the whole time 😓 .

Thanks for the help @purrloftruth . 😄 
I hope you get better 😡

**Comment by purrloftruth** [comment]
That’s one way to do it! You can also use the key shortcut `Shift+Command+G` — this brings up a dialog in your Finder window that lets you input an arbitrary path to navigate to (such as, for example, `~/Library/Application Support/TuneOut`). Library also temporarily appears if you hold `Option` while you’re in the `Go` menu of Finder’s Menu Bar. Glad you were able to get everything working!
On Mar 22, 2019, 6:24 AM -0400, Dylan Landry <notifications@github.com>, wrote:

I was looking in the wrong folder — in /Library/Application Support ! I did not know you had to manually reveal your ~/Library folder by navigating to your home directory, clicking View -> Show View Options, then Show Library Folder. The directory may have been there the whole time 😓 .

Thanks for the help @purrloftruth<https://github.com/purrloftruth> . 😄
I hope you get better 😡
